src/Prospectiva/ExerciceBundle/Entity/Contrat.php
<?php

namespace Prospectiva\ExerciceBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

use Prospectiva\ExerciceBundle\Entity\Interimaire;
use Prospectiva\ExerciceBundle\DBAL\EnumContratStatut;

/**
 * @ORM\Entity(repositoryClass="Prospectiva\ExerciceBundle\Repository\ContratRepository")
 * @ORM\Table(name="contrat")
 */
class Contrat
{    
    /**
     * @ORM\Id 
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     **/
   private $id_contrat;
      
   /** 
    * @ORM\Column(type="datetime", nullable=false) 
    * @Assert\NotBlank()
    * @Assert\DateTime()
    */
   private $debut;
   
   /** 
    * @ORM\Column(type="datetime", nullable=false) 
    * @Assert\NotBlank()
    * @Assert\DateTime()
    * @Assert\Expression(
    *   "this.getFin() > this.getDebut()",
    *   message="La date de fin doit être supérieur à la date de début"
    * )
    */
   private $fin;
   
   /** 
    * @ORM\Column(type="enumcontratstatut", nullable=false) 
    * @Assert\NotBlank()
    * @Assert\Choice(callback="getAuthorizedStatut")
    * 
    */
   private $statut;
   
   /**
    * @ORM\ManyToOne(targetEntity="Interimaire")
    * @ORM\JoinColumn(name="id_interimaire", referencedColumnName="id_interimaire", nullable=false)
    * @Assert\NotBlank()
    */
   private $interimaire;
   
   /**
    * @ORM\Column(type="boolean", options={"default" : false})
    */
   private $visible = true;
   
   public function getIdContrat() {
       return $this->id_contrat;
   }

   public function getDebut() {
       return $this->debut;
   }

   public function getFin() {
       return $this->fin;
   }

   public function getStatut() {
       return $this->statut;
   }

   public function getInterimaire() {
       return $this->interimaire;
   }
   
   public function getVisible() {
       return $this->visible;
   }

   public function setDebut(\DateTime $debut) {
       $this->debut = $debut;
   }

   public function setFin(\DateTime $fin) {
       $this->fin = $fin;
   }

   public function setStatut($statut) {
       $this->statut = $statut;
   }

   public function setInterimaire(Interimaire $interimaire) {
       $this->interimaire = $interimaire;
   }
   
   public function setVisible($visible) {
       $this->visible = $visible;
   }

   public static function getAuthorizedStatut()
   {
        return EnumContratStatut::getValues();
   }
}

src/Prospectiva/ExerciceBundle/Form/ContratType.php
<?php

namespace Prospectiva\ExerciceBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

use Doctrine\Common\Persistence\ObjectManager;
use Prospectiva\ExerciceBundle\Form\EntityHiddenTransformer;
use Prospectiva\ExerciceBundle\DBAL\EnumContratStatut;
use Prospectiva\ExerciceBundle\Entity\Interimaire;
use Prospectiva\ExerciceBundle\Entity\Contrat;


class ContratType extends AbstractType
{
    private $_objectManager;
    
    public function __construct(ObjectManager $objectManager)
    {
        $this->_objectManager = $objectManager;
    }
    
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $hiddenTransformer = new EntityHiddenTransformer(
            $this->_objectManager,
            Interimaire::class,
            'id_interimaire'
        );
        
        $attr = array('class' => 'autocomplete');
        $attr['data_single_result'] = $options['single_result_route'];
        $attr['data_multiple_result'] = $options['multiple_result_route'];
        $attr['autocomplete'] = 'disabled';
        
        $builder
            ->add(
               $builder->create('interimaire', HiddenType::class)
               ->addModelTransformer($hiddenTransformer)
            )
            ->add('interimaire_autocomplete', TextType::class, array(
                'label' => 'Interimaire',
                'attr'=> $attr,
                'mapped' => false
             ))
            ->add('debut', DateType::class, array(
                'widget' => 'choice'
             ))
            ->add('fin', DateType::class, array(
                'widget' => 'choice'
             ))
            ->add('statut', ChoiceType::class , array(
                'choices' => EnumContratStatut::getLabel()
             ))
            ->add('enregistrer', SubmitType::class, array('label' => 'Enregistrer', 
                'attr' => array('class' => 'btn-primary')
             ));
    }
    
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setRequired(array('single_result_route', 'multiple_result_route'));
        $resolver->setDefaults(array(
            'data_class' => Contrat::class,
        ));
    }
}

src/Prospectiva/ExerciceBundle/Controller/ContratController.php
<?php

namespace Prospectiva\ExerciceBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Prospectiva\ExerciceBundle\Entity\Contrat;
use Prospectiva\ExerciceBundle\Form\ContratType;

class ContratController extends Controller
{
    /**
     * @Route("/", name="listContrat")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $contrats = $em->getRepository(Contrat::class)->listContratWithInterimaire();
         
        return $this->render('@ProspectivaExercice/contrat/index.html.twig', array(
            'contrats' => $contrats
        ));
    }
        
    /**
     * @Route("/edit/{id_contrat}", name="editContrat", requirements={"id_contrat"="\d+"})
     * @Route("/create", name="createContrat")
     */
    public function updateAction(Request $request, $id_contrat = null)
    {
        $em = $this->getDoctrine()->getManager();
        $contrat = new Contrat();
        
        if($id_contrat !== null) {                        
            $requestedContrat = $em->getRepository(Contrat::class)->getContratWithInterimaire($id_contrat);
            $contrat = $requestedContrat !== null ? $requestedContrat : $contrat;
        }
                
        $singleResultRoute = $this->generateUrl('getInterimaire');
        $multipleResultRoute = $this->generateUrl('searchInterimaire');
        
        $form = $this->createForm(ContratType::class, $contrat, array(
            'single_result_route' => $singleResultRoute,
            'multiple_result_route' => $multipleResultRoute
        ));
        $form->handleRequest($request);
        
        if($form->isSubmitted() && $form->isValid()){
            $formData = $form->getData();
            
            $em->persist($formData);
            $em->flush();
            
            $this->addFlash("success", "Vos modifications ont bien été prises en compte");
            if($id_contrat !== null) {
                return $this->redirectToRoute("editContrat", array('id_contrat' => $id_contrat));
            } else {
                return $this->redirectToRoute("listContrat");
            }
        }
                
        $response = $this->render('@ProspectivaExercice/contrat/update.html.twig', array(
            'form' => $form->createView(),
            'contrat' => $contrat
        ));
        
        $response->headers->addCacheControlDirective('no-cache', true);
        $response->headers->addCacheControlDirective('max-age', 0);
        $response->headers->addCacheControlDirective('must-revalidate', true);
        $response->headers->addCacheControlDirective('no-store', true);
        
        return $response;
    }
    
    /**
     * @Route("/delete/{id_contrat}", name="deleteContrat")
     */
    public function deleteAction(Request $request, $id_contrat = null)
    {
        $em = $this->getDoctrine()->getManager();
        $contrat = $em->getRepository(Contrat::class)->find($id_contrat);
        
        if($contrat !== null) {
            $contrat->setVisible(false);
            $em->persist($contrat);
            $em->flush();
            
            $this->addFlash("success", "Vos modifications ont bien été prises en compte");
        }
        
        return $this->redirectToRoute("listContrat");
    }
}

src/Prospectiva/ExerciceBundle/Resources/views/contrat/index.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="container">
        <h3>Liste des contrats</h3>
        
        <table class="table">
            <thead>
                <th scope="col">Prénom</th>
                <th scope="col">Nom</th>
                <th scope="col">Debut</th>
                <th scope="col">Fin</th>
                <th scope="col">Statut</th>
                <th></th>
            </thead>
            <tbody>
                {% for contrat in contrats %}
                    <tr>
                        <th scope="row">{{contrat.interimaire.prenom|capitalize}}</th>
                        <td>{{contrat.interimaire.nom|upper}}</td>
                        <td>{{contrat.debut|date('d/m/Y')}}</td>
                        <td>{{contrat.fin|date('d/m/Y')}}</td>
                        <td>{{contrat.statut}}</td>
                        <td>
                            <a href="{{path('editContrat')}}/{{contrat.idContrat}}" 
                               style="margin-right: 10px;">Modifier</a>
                            <a class="delete" 
                               data-confirm="Etes vous sur de vouloir supprimer cette ligne ?"
                               data-redirect="{{path('deleteContrat')}}/{{contrat.idContrat}}"
                            >Supprimer</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div>
            <a style="float:right;" href="{{path('createContrat')}}">Ajouter</a>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(function(){
           $('table .delete').on('click', function(){
               var message = $(this).attr('data-confirm');
               var redirectUrl = $(this).attr('data-redirect');
               
               var shouldProceed = confirm("Etes vous sur de vouloir supprimer cette ligne ?");
               if(shouldProceed) {
                   window.location.href = redirectUrl;
               }
           }) 
        });
    </script>
{% endblock %}

src/Prospectiva/ExerciceBundle/Resources/views/contrat/update.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="container">
        {% if contrat.getIdContrat() is not null %}
            <h3>Modification du contrat {{contrat.interimaire.prenom}} {{contrat.interimaire.nom|upper}} - {{contrat.debut|date("d/m/Y")}}</h3>
        {% else %}
            <h3>Création d'un nouveau contrat</h3>
        {% endif %}
        
        <p>
            Saisissez "Fab" dans le champs interimaire, afin d'obtenir des données lors de la recherche ajax
        </p>
        
        {{ form_start(form, {'attr': {'novalidate': 'novalidate', 'method': 'post'}}) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>
{% endblock %}